services:
  - type: web
    name: geodeterminants-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    branch: master
    healthCheckPath: /
    envVars:
      - key: CENSUS_API_KEY
        sync: false
